openapi: "3.0.3"
info:
  title: openapi template
  version: 1.0.0
  description:
servers:
  - url: http://localhost:8080
    description: local environment
  - url: https://go-server-poc-2ra7djjztq-an.a.run.app
    description: production environment
paths:
  /:
    get:
      description: |
        Check the availability of server.
      operationId: getPing
      responses:
        '200':
          description: succeed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPingResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /health:
    get:
      description: |
        Check the availability of server and database.
      operationId: getHealth
      responses:
        '200':
          description: succeed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHealthResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /health/auth:
    get:
      description: |
        Test the availability of firebase authorization.
      operationId: getHealthAuth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: succeed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHealthAuthResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/signup:
    post:
      description: |
        Create new user.
      operationId: postAuthSignup
      security:
        - bearerAuth: []
      parameters:
        - name: userName
          in: query
          required: true
          style: form
          schema:
            type: string
        - name: userId
          description: User ID generated by Firebase as uid.
          in: query
          required: true
          style: form
          schema:
            type: string
      responses:
        '204':
          description: succeed
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /user/{userId}:
    get:
      description: |
        Get user information.
      operationId: getUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: succeed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    GetPingResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: ok
          description: Server status.
    GetHealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: ok
          description: Server and DB status.
    GetHealthAuthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: ok
          description: Auth status.
    GetUserResponse:
      type: object
      required:
        - userName
      properties:
        userName:
          type: string
          example: Kishida Nobuo
    ErrorResponse:
      type: object
      required:
        - statusCode
        - message
      properties:
        statusCode:
          type: integer
          example: 401
          description: HTTP status code.
        title:
          type: string
          example: Unauthorized
          description: Short error code or identifier.
        message:
          type: string
          example: 
          description: Human-readable error message.
