openapi: "3.1.0"
info:
  title: openapi template
  version: 1.0.0
  description:
servers:
  - url: http://localhost:8080
    description: local environment
  - url: http://production.com
    description: production environment
paths:
  /ping:
    get:
      description: |
        SSIA.
      operationId: getPing
      parameters: []
      responses:
        '200':
          description: succeed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPingResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /health:
    get:
      description: |
        Check the availability of server.
      operationId: getHealth
      parameters: []
      responses:
        '200':
          description: succeed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHealthResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    GetPingResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: ok
          description: Server status.
    GetHealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: ok
          description: Server and DB status.
    Error:
      type: object
      required:
        - statusCode
        - message
      properties:
        statusCode:
          type: integer
          example: 401
          description: HTTP status code.
        title:
          type: string
          example: Unauthorized
          description: Short error code or identifier.
        message:
          type: string
          example: 
          description: Human-readable error message.
