openapi: "3.1.0"
info:
  title: openapi template
  version: 1.0.0
  description:
servers:
  - url: http://localhost:8080
    description: local environment
  - url: https://go-server-poc-2ra7djjztq-an.a.run.app
    description: production environment
paths:
  /:
    get:
      description: |
        Check the availability of server.
      operationId: getPing
      parameters: []
      responses:
        '200':
          description: succeed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPingResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /health:
    get:
      description: |
        Check the availability of server and database.
      operationId: getHealth
      parameters: []
      responses:
        '200':
          description: succeed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHealthResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /health/auth:
    get:
      description: |
        Test the availability of firebase authorization.
      operationId: getHealthAuth
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: succeed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getHealthAuthResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    GetPingResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: ok
          description: Server status.
    GetHealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: ok
          description: Server and DB status.
    getHealthAuthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: ok
          description: Auth status.
    Error:
      type: object
      required:
        - statusCode
        - message
      properties:
        statusCode:
          type: integer
          example: 401
          description: HTTP status code.
        title:
          type: string
          example: Unauthorized
          description: Short error code or identifier.
        message:
          type: string
          example: 
          description: Human-readable error message.
