openapi: "3.1.0"
info:
  title: openapi template
  version: 1.0.0
  description:
servers:
  - url: http://localhost:8000
    description: local environment
  - url: http://production.com
    description: production environment
paths:
  /health:
    get:
      description: |
        Check the availability of server.
      operationId: getHealth
      parameters: []
      responses:
        '200':
          description: succeed
          content:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - statusCode
        - message
      properties:
        statusCode:
          type: integer
          example: 401
          description: HTTP status code.
        title:
          type: string
          example: Unauthorized
          description: Short error code or identifier.
        message:
          type: string
          example: 
          description: Human-readable error message.
