// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package openapi

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Human-readable error message.
	Message string `json:"message"`

	// StatusCode HTTP status code.
	StatusCode int `json:"statusCode"`

	// Title Short error code or identifier.
	Title *string `json:"title,omitempty"`
}

// GetHealthAuthResponse defines model for GetHealthAuthResponse.
type GetHealthAuthResponse struct {
	// Status Auth status.
	Status string `json:"status"`
}

// GetHealthResponse defines model for GetHealthResponse.
type GetHealthResponse struct {
	// Status Server and DB status.
	Status string `json:"status"`
}

// GetPingResponse defines model for GetPingResponse.
type GetPingResponse struct {
	// Status Server status.
	Status string `json:"status"`
}

// GetUserResponse defines model for GetUserResponse.
type GetUserResponse struct {
	UserName string `json:"userName"`
}

// PostAuthSignupParams defines parameters for PostAuthSignup.
type PostAuthSignupParams struct {
	UserName string `form:"userName" json:"userName"`

	// UserId User ID generated by Firebase as uid.
	UserId string `form:"userId" json:"userId"`
}
