// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package openapi

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	// Message Human-readable error message.
	Message string `json:"message"`

	// StatusCode HTTP status code.
	StatusCode int `json:"statusCode"`

	// Title Short error code or identifier.
	Title *string `json:"title,omitempty"`
}

// GetHealthResponse defines model for GetHealthResponse.
type GetHealthResponse struct {
	// Status Server and DB status.
	Status string `json:"status"`
}

// GetPingResponse defines model for GetPingResponse.
type GetPingResponse struct {
	// Status Server status.
	Status string `json:"status"`
}

// GetHealthAuthResponse defines model for getHealthAuthResponse.
type GetHealthAuthResponse struct {
	// Status Auth status.
	Status string `json:"status"`
}
