name: make gen
on: 
  push:
jobs:
  make-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'
      - uses: actions/checkout@v3
      - name: Run make build-tools
        run: make build-tools
      - name: Run make gen
        run: make gen
      - name: Check for diffs
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected after running make gen:"
            git status --porcelain
            git diff
            exit 1
          else
            echo "No changes detected after running make gen."
          fi
